### ISSUE TITLE
Create a Triton backend

### ISSUE THREAD

**Issue by EwoutH** [astramind-ai/BitMat#2]
Would it be possible to create a [Triton backend](https://github.com/triton-inference-server/backend) from this implementation?

> A Triton backend is the implementation that executes a model. A backend can be a wrapper around a deep-learning framework, like PyTorch, TensorFlow, TensorRT or ONNX Runtime. Or a backend can be custom C/C++ logic performing any operation (for example, image pre-processing).

**Comment by mlinmg** [comment]
I don't have direct experience with Triton-Inference-Server, I'll look into it in the nex days

**Comment by michaelfeil** [comment]
@EwoutH I think you confused OpenAI Triton (the Language) with Nvidia Triton (a API server in C++)

**Comment by EwoutH** [comment]
Right, from the Readme I didn’t figure that. Thanks for clearing that up!
