### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Weroxig** [astramind-ai/BitMat#3]
I was trying to run the demo code, but it fails on import
```python
ImportError: cannot import name 'convert_hf_model' from partially initialized module 'bitmat' (most likely due to a circular import) 
```
```python
from transformers import AutoModelForCausalLM
from bitmat import convert_hf_model

# Initialize your model from an available hf model
model= AutoModelForCausalLM.from_pretrained("some-repo/some-model")
# Convert the model to use BitLinear layers
model = convert_hf_model(model)
# Save the converted model
model.save_pretrained('some_local_folder')
```

Installed from git with `pip install git+https://github.com/astramind-ai/BitMat.git` (bitmat-tl version 0.2.5)

**Comment by mlinmg** [comment]
It had been taken care of in 0.2.8
Please install lst by doing _pip install -U bitmat-tl_

**Comment by Weroxig** [comment]
Updated to 0.2.8 but it seems that there is still the same problem. I also tried making a new python venv and installing only bitmat-ml 0.2.8, but it still gives:
`ImportError: cannot import name 'convert_hf_model' from partially initialized module 'bitmat' (most likely due to a circular import)`

**Comment by mlinmg** [comment]
It doesn't shows any error from my env. 
Please try:
```bash
pip3 uninstall bitmat-tl 
```
then 
```bash
pip3 install bitmat-tl --no-cache-dir
```

**Comment by Weroxig** [comment]
oops, it was because I decided to use the filename bitmat.py as the test file for the demo.
