### ISSUE TITLE
Training without full precision

### ISSUE THREAD

**Issue by Sneakr** [astramind-ai/BitMat#8]
Is it possible to train in quantized mode without full precision? Could maybe use 2-bit quant to hold the ternary values? Thanks

**Comment by GiacomoLeoneMaria** [comment]
During training, when calling torch train methods, the BitLinear class is called by applying a surclass of $nn.module$ by registering the weights as buffers instead of being instantiated as parameters; this is necessary because $int8$ cannot be used with torch $nn.parameter$
