### ISSUE TITLE
ValueError: Pointer argument (at 2) cannot be accessed from Triton (cpu tensor?)

### ISSUE THREAD

**Issue by namtranase** [astramind-ai/BitMat#9]
Thank you for the awesome repo. I have successfully converted the mistral model to the 158 version, but I got the error when trying the inference phase.
The code:
```
from bitmat import Auto158ModelForCausalLM
from transformers import AutoTokenizer

# Replace 'path_to_your_model' with the actual path to your model's directory
model = Auto158ModelForCausalLM.from_pretrained('/Mistral-7B-Instruct-v0.2-bitmat')
tokenizer = AutoTokenizer.from_pretrained("/Mistral-7B-Instruct-v0.2")


prompt = "Hey, are you conscious? Can you talk to me?"
inputs = tokenizer(prompt, return_tensors="pt")
# Generate
generate_ids = model.generate(inputs.input_ids, max_length=30)
output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
print(output)
```
The error:
```
ValueError: Pointer argument (at 2) cannot be accessed from Triton (cpu tensor?)
```

**Comment by mlinmg** [comment]
Triton can only work with tensors on the gpu. 
If you have an Nvidia GPU you  need to call `inputs = tokenizer(prompt, return_tensors="pt")`**`.cuda()`**, 
as well as `Auto158ModelForCausalLM.from_pretrained('/Mistral-7B-Instruct-v0.2-bitmat')`**`.cuda()`**
If you have other gpu types you'll need to call the corresponding methods

**Comment by namtranase** [comment]
Thank you for the response, I have loaded the model and input into the same gpu (also check the W and x in codebase), but I got the error in the quantize_activations step:
 ```
File "BitMat/bitmat/utils/bitmat.py", line 22, in quantize_activations
    scale = (127 / torch.max(x.abs().max(dim=-1).values, torch.tensor(1e-5))).unsqueeze(-1)
```
 ```
    RuntimeError: CUDA error: an illegal memory access was encountered
 ```
 I try to use the A30 card in my experiment.
Any recommendation on this will be really helpful. I will try to fix the problem

**Comment by mlinmg** [comment]
I think it is related with #7, the illegal memory access is not directly related with the quantize_activations but rather the kernel that messes up cuda and the next operation done in cuda throws the error. you can refer the issue 7 if you want to investigate, atm we're doing lots of experimentation but we can't pinpoint the issue

**Comment by namtranase** [comment]
I have interesting experiments:
- Load Mistral with 5 layers -> inference works fine
- Load > 10 layers -> false
- And tried the playground method like you suggested to pass the error, it passed but I got other issues. I think after the matmul kernel is fixed, all of these bugs will be killed

**Comment by mlinmg** [comment]
Thank you for your commitment! Yes we're currenty investigating the root cause of the bug, stay tuned in the next days a fix will be pushed
